In [1]:
import numpy

class matrix_factorization():
    
    def __init__(self,R,a,b,it,k):
        self.R=R
        self.user_n, self.item_n=R.shape
        self.alpha=a
        self.beta=b
        self.iterations=it
        self.K=k
        
    def learn(self):
        self.b_users=numpy.zeros(self.user_n)
        self.b_items=numpy.zeros(self.item_n)
        self.b=numpy.mean(self.R[numpy.where(self.R!=0)])
        
        self.P=numpy.random.normal(scale=1./self.K,size=(self.user_n,self.K))
        self.Q=numpy.random.normal(scale=1./self.K,size=(self.item_n,self.K))
        rng=numpy.random.default_rng()
        
        self.samples=[]
        for i in range (self.user_n):
            for j in range (self.item_n):
                if (self.R[i][j])!=0:
                    self.samples.append((i,j,self.R[i][j]))

        for i in range (self.iterations):
            samplesize=min(100,len(self.samples))
            self.samplegroup=rng.choice(self.samples,samplesize,False)
            self.sgd()
        self.leastCertain()
            
    def leastCertain(self):
        Q=numpy.absolute(self.complete())
        i=numpy.argmin(Q)
        print("Least Certain Value Indexes: ")
        print(numpy.unravel_index(i,Q.shape))
        
    def sgd(self):
        for i, j, r in self.samplegroup:
            prediction = self.b_users[i]+self.b_items[j]+self.b+self.P[i,:].dot(self.Q[j,:].T)
            e = (r - prediction)
            
            self.b_users[i]+=self.alpha*(e-self.beta*self.b_users[i])
            self.b_items[j]+=self.alpha*(e-self.beta*self.b_items[j])
            
            self.P[i,:]+=self.alpha*(e*self.Q[j,:]-self.beta*self.P[i,:])
            self.Q[j,:]+=self.alpha*(e*self.P[i,:]-self.beta*self.Q[j,:])
            
    def get_rating(self,i,j):
        return self.b_users[i]+self.b_items[j]+self.b+self.P[i,:].dot(self.Q[j,:].T)
    
    def complete(self):
        return self.P.dot(self.Q.T)+self.b+self.b_users[:,numpy.newaxis]+self.b_items[numpy.newaxis,:]
        

In [2]:
M = numpy.array([
    [1, -1, 0, 1],
    [1, 0, -1, 1],
    [-1, -1, 1, 1],
    [1, 0, 0, -1],
    [0, 1, 0, -1],
])

mf = matrix_factorization(M, 0.1, 0.01, 10, 3)

mf.learn()

print(numpy.around(mf.complete(),2))


Least Certain Value Indexes: 
(0, 2)
[[ 1.03 -0.98  0.17  1.04]
 [ 1.16 -0.18 -0.68  0.56]
 [-0.96 -0.98  0.95  1.04]
 [ 0.82 -1.06 -1.08 -0.55]
 [-0.48  0.97 -1.15 -0.82]]
